### ISSUE TITLE
Code highlighting didn't work

### ISSUE THREAD

**Issue by Taolaw** [tzvetkov75/solar-theme-hexo#6]
Hello,Thanks for the theme you designed, but after I configured it according to the method given by your README, in my blog, the code highlights and doesn't work, the black background and the black words make people feel bad. In the solar directory, the highlight configuration used in _config.yml is the default. What is the cause of this problem?

**Comment by Taolaw** [comment]
My blog link : https://taolaw.github.io/
I have wasted a morning for this highlighted configuration, I hope you can help me.
Thanks!

**Comment by tzvetkov75** [comment]
Hi,  I am happy the hear that you like the theme.
Can you try to define the code blog usingdifferent language attribute as here (key word javascript) 

``` javascript
<script type="text/javascript">
function intArraySort(c, a) {  
    function d(a, b) { return b - a; }
    "string" == typeof a && a.toLowerCase(); 
    switch (a) {               
        default: return c.sort(function(a, b) { return a - b; });
        case 1:                
                case "d":      test1             
    } 
};
</script>
```     

I hope this will help. Do not forget to git star the repo if you like it  :-)

**Comment by Taolaw** [comment]
Sorry, I still can't solve the problem I faced with the above method. Here is my `_config.yml `configuration about code highlighting. It defaults to` lightcode`. I see a lot of highlighting styles in the `source/_highlight/ directory`. What is the relationship between these files and the configuration here? How to make the code highlight like the one given in your `demo`, I hope you have time to help solve my doubts, thank you!
```
# eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.jpeg
        gravatar: false
      android:
        url: /images/favicon-192x192.jpeg
        gravator: false
      apple:
        url: /images/apple-touch-icon.jpeg
        gravator: false
    social_links:
        github: https://github.com/tzvetkov75/solar-theme-hexo
        twitter: /
        facebook: /
        linkedin: /
    post_count: 5
    highlight: monokai-sublime
```
